name: 404 micro-frontend deployment

on:
  push:
    branches:
      - 404
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_404_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "404"

